config/routes.rb
Rails.application.routes.draw do
  
  # get 'pages/home'
  root 'todos#index'
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todo = Todo.new
    @todos = Todo.all
    
  end

  

  def create 
    @todo = Todo.new(todo_params)
    if @todo.save
      flash.now[:success] = "Todo was successfully created"
      redirect_to todos_path
    else
      flash.now[:danger] ="Nope... Try it again"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update 
    if @todo.update(todo_params)
      flash.now[:success] = "Todo was successfully Updated"
      redirect_to todos_path
    else
      flash.now[:danger] = "That didn't work well! try again..."
      render 'edit'
    end
  end

  def destroy 
    @todo.destroy
    flash.now[:success] = "Todo was deleted"
    redirect_to todos_path
  end

  private 

  def todo_params 
    params.require(:todo).permit(:name, :description)
  end

  def set_todo 
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_flash.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
          </button>
          <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Home", todos_path %></li>
            
            <!-- <li class="divider"></li> -->
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Add Item", new_todo_path %></li>
            <li><%= link_to "List", todos_path %></li>
          </ul> 
          </div>
        </nav>
        <span class="nav-title mobile">Shopping List</span>
      </div>
    
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoOffline</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,600;1,500&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash" %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1 class="center">To Do (Offline Version)</h1>
</div>


<div class="well">
 <h4 class="text center home-text">Hello and welcome to the To Do app. This is just like a Chores list 
 you create at home where you can add a chore and delete it once its done. You can even use this offline!</h4>
</div>

<div class="container">
  
    <div>
      
      <%= link_to "Create a Todo", new_todo_path, class: "btn btn-default btn-lg " %>
    
    </div>
  
</div>

app/views/todos/_errors.html.erb
<% if @todo.errors.any? %>
 <div class="row">
  <div class="col-md-8 col-md-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
    <h2 class="panel-title">
      <%= pluralize(@todo.errors.count, "error") %> prohibited this <%= @todo.class %> from being saved: <!-- Solution from recipes_test_rb 46 -->
     </h2>
      <div class="panel-body">
       <ul>
        <% @todo.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
      <% end %>
     </ul>
    </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/todos/_form.html.erb
<div class="row">
  <div class="col-md-12 mobile-form">
  
        
          <%= form_for(@todo, :html => {class: "form-horizontal", role: "form"}) do |f| %>
          
           <div class="form-group">
             <div class="control-label col-md-2">
             </div>
             <div class="col-md-4 col-md-offset-2">
              <%= f.label :item, class: "pull-left" %> 
               <%= f.text_field :name, class: 'form-control', placeholder: "Add Item", autofocus: true %>
             </div>
           </div>
          
          
          
          
          
          <div class="form-group">
            <div class=" col-md-4 col-md-offset-4">
              <%= f.submit "Add to List", class: "btn btn-primary btn-sm form-button" %> 
              <%#= link_to "Back to Index", todos_path, class: "btn btn-warning" %>
            </div>
          </div>
        
        <% end %>
      </p>
   
  </div>
</div>

app/views/todos/edit.html.erb
 <div class="row">
  <h2 class="text-center">Edit your To Do</h2>
</div> 

<%= render "todos/errors" %>

<%= render "todos/form" %>

app/views/todos/index.html.erb
  <div class="row">
    <h1 class="center page-title">Shopping List</h1>
    <div class="center">
        <p>
          <%#= link_to "Create a To Do", new_todo_path, class: "btn btn-success" %>
        </p>
        <%= render "todos/form" %> 
           <div class="center">
             <% @todos.each do |todo| %>
             <div class="col-md-4 col-md-offset-4 item-body">
               <span class="descriptionText"> <%= todo.name %></span><br />
              <!-- <p>Description: <%#= todo.description %></p> -->
               
                  <%= link_to "Delete", todo_path(todo), method: :delete,  class: "btn btn-danger btn-xs" %>
             
             </div>
           <% end %>
        </div>
    </div>
  </div>

app/views/todos/show.html.erb
<div class="row">
    <h2 class="text-center">My To Do</h2>
      <div class="col-md-4 col-md-offset-4">
        <div class="well">
          <p><span class="descriptionText">Name:</span> <%= @todo.name %></p>
            <br />
            <p><span class="descriptionText">Description:</span> <%= @todo.description %></p>
             <p>
                <%= link_to "Edit This To Do", edit_todo_path(@todo), class: "btn btn-primary bttn" %> 
                <%= link_to "Back to Index", todos_path, class: "btn btn-warning bttn" %>
            </p>
        </div>
      </div>